name: Linter

on:
  pull_request:
    branches: [ main ]

jobs:
  linting:
    name: GH Super-Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: JS/CSS linting
        uses: github/super-linter/slim@v4.9.4
        env:
          LINTER_RULES_PATH: /
          VALIDATE_CSS: true
          VALIDATE_JAVASCRIPT_ES: true
          JAVASCRIPT_ES_CONFIG_FILE: sl-eslint.js
          VALIDATE_HTML: true
          FILTER_REGEX_EXCLUDE: (assets/.*\.css)
          GITHUB_TOKEN: ${{ github.token }}
          DEFAULT_BRANCH: main
