name: Theme Check

on:
  push:
    # paths-ignore:
    #   - 'assets/et_theme.js'
    #   - 'assets/et_theme.css'

jobs:
  shopify-theme-check:
    name: Shopify Theme Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Theme Check and Liquid linting
        uses: shopify/theme-check-action@v1.2.3
        with:
          # flags: ''
          token: ${{ github.token }}
          base: main
